name: Build Website
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'src/**'
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-literate-nav
      - run: pip install mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy --force
